#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

skip_linters+=(
    ansible-lint
    yamllint
)

# Explicit excludes, give entire filepath as listed by olint
excludes+=(
    # README.md
    # bin/list-all
)

# override_linter_cmd["checkbashisms"]="checkbashisms --config .checkbashisms"
override_linter_cmd["codespell"]="codespell -H -S './.git,./.venv,./.mypy_cache' -S ./bin_user/Linux/dropbox.py"
